### PR TITLE
Annotted 

### PR DESCRIPTION
**Pull request by sumanthshankar**
Manish i have annotated Answer.java, Multiplechoice.java, Textareaanswer.java, Textboxanswer.java, Choices.java

### CODE REVIEW

**Review by amanish05 — CHANGES_REQUESTED** [review]
Sumanth, There is total of 29 files shows changes and that too every file is replaced. I can't see what are the specific changes you have done. I'm not merging the file because it might create problem to our main master. Also their are some unnecessary files in your commit. You might clone or rebase the project and make necessary changes.

**Comment by sumanthshankar** [comment]
There was a problem when copying from pendrive so to undo it i had to
delete because of this it shows 29 files replaced. So what i will do is
delete my existing repository make a fresh copy from yours & make the
changes & i will push it back & i will send a pull request.

**Comment by amanish05** [comment]
I Understand it.  If I will merge this,  It will replace all our master file from your's. Please clone/rebase again and replace with your answers. Also remove all un-necessary files from your commit.

**Comment by sumanthshankar** [comment]
Sure. Can i clone from the master now? Because u said latest code from Yuan
has problems.

**Pull request closed without merging**
